### ISSUE TITLE
Invalid SSL certificate on BoxStarter.org

### ISSUE THREAD

**Issue by ghuntley** [chocolatey/boxstarter#106]
<img width="683" alt="screen shot 2015-08-28 at 10 21 09 am" src="https://cloud.githubusercontent.com/assets/127353/9536391/8d97810c-4d6e-11e5-93ee-c633dc11f2c6.png">
# Problem

```
Start -> Run ->

iexplore http://boxstarter.org/package/nr/url?https://raw.githubusercontent.com/ghuntley/dotfiles-windows/master/desktop.boxstarter 
```

Will download/initiate the boxstarter bootstrap application via an unsecured SSL connection which means on an untrusted network link it is a vector available to cause malicious damage.

Accessing via  https://boxstarter.org will result in above SSL error
# Resolution
- Obtain SSL certificate - $20bux for three years @ https://www.gogetssl.com/domain-validation/comodo-essentialssl/ 
- Install SSL certificate into website management panel on azure.

**Comment by mwrock** [comment]
Agreed. Need to do this.

**Comment by ghuntley** [comment]
Boop, beep. LetsEncrypt launches tomorrow. Can the maintainer of the website signup and install a cert - it will cost you nothing.

**Comment by ghuntley** [comment]
https://letsencrypt.org/2015/12/03/entering-public-beta.html

**Comment by mwrock** [comment]
Yeah when I get around to this, letsencrypt will likely be the path I take.

**Comment by dragon788** [comment]
When attempting to launch Boxstarter via the web it fails because the site certificate isn't valid/trusted by the ClickOnce launcher. I was able to work around this by installing Boxstarter via Chocolatey and then installing the gist by calling Install-BoxstarterPackage, but that's only because I already had chocolatey available.

This appears to be compounding the issue of being behind a Bluecoat network inspection appliance that replaces/assumes authority over SSL certificates and requires being installed as a trusted CA on machines.

**Comment by ryanspletzer** [comment]
*bump*

**Comment by berney** [comment]
I think you need to do this, when you download the the zip file, and unzip it, the powershell script isn't signed and the batch file runs the powershell script with executionpolicy bypassed. It will be trivial for a MitM to rewrite these's on the fly to trojan them.

**Comment by jlandheer** [comment]
Can this get a signal boost? Personally I think that in this day and age not having a valid certificate (and not using https exclusively) for a tool using administrative rights is a bit of a risk and could prevent adoption.

**Comment by filhit** [comment]
_bump_

**Comment by Redsandro** [comment]
**Boxstarter** is giving problems on the `https` version of [WindowsRemix](https://windowsremix.com/software) with Firefox 58 using my [ClickOnce Helper](https://addons.mozilla.org/en-US/firefox/addon/clickonce-helper/) plugin. Even when I implement a `https` proxy that redirects to the `http` Boxstarter, Firefox still catches the 'unsafe' redirect and blocks it. Theoretically this is a neat feature of Firefox. In reality it's no big secret someone is installing FOSS or Freemium over Boxstarter.

However realistically, I agree with @jlandheer. In this day and age, Google, Firefox and Chrome all expect https.

@mwrock is there anything I can do to help? What is your webserver software? Do you have a complete list of subdomains Boxstarter is using? Who is your webhost? Do you use Azure with IIS? [Is this helpful](https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/20047)?

**Comment by mrled** [comment]
Hello, chiming in to request some attention on this issue as well. I have seen some cool posts on Boxstarter recent, but I think HTTPS is too important for me to be comfortable without it. Is there anything I could do to help?

**Comment by Redsandro** [comment]
@mrled do you know anything about IIS? I'm a linux man myself, so I don't recognize the files. But perhaps you can take a look at https://github.com/mwrock/boxstarter/tree/master/Web and see if something like _LetsEncrypt_ can be added through a pull-request.

The acme shellscripts for apache don't work (obviously) but perhaps the link in my previous message as some hints about how to do this in IIS.

**Comment by mrled** [comment]
@Redsandro it looks like there isn't a code change required to use Let's Encrypt with an Azure Website. From what I can tell from your link, it just needs someone with access to the Azure account where boxstarter.org is being hosted to change some settings in the portal.

**Comment by mwrock** [comment]
Sorry for not responding sooner. The problem I see with the letsencrypt extension is that according to that post, it needs a beefier Azure plan. I'm on a shared plan which is even below basic. Scaling up is way too expensive.

I totally get that HTTPS is preferable but the fact is that everything served over HTTP in Boxstarter is just a static web site for documentation. I stopped supporting the web installer to eliminate the burden of the code signing cert. In fact I wonder if that is why @Redsandro is having the "unsafe" issue because the current unsupported installer's signing cert has long expired.

If you do want that functionality, I'd encourage you to host your own installer on your own domain. You could probably do that fairly easily by cargo culting the existing click-once assembly in this repo.

**Comment by Redsandro** [comment]
Hi @mwrock, I didn't know the webinstaller was no longer supported and the expired certificate might be the problem. But I found the [blog item](http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher).

> If you do want that functionality, I'd encourage you to host your own installer on your own domain. You could probably do that fairly easily by cargo culting the existing click-once assembly in this repo.

Would love to try this. Can you point out which files are needed solely for the web launcher?

**Comment by Redsandro** [comment]
Hi @mwrock I read in the [disqus comments](http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher#comment-3379814564) that @ferventcoder had offered to help out with keeping the Web Installer alive. Have you guys discussed this further?

I'd also like to see some bandwidth statistics in order to estimate if I could take it.

**Comment by mrled** [comment]
@mwrock oh, I didn't realize the WebLauncher was no longer supported - I didn't really see anything to that effect here: http://boxstarter.org/Learn/WebLauncher

What is the preferred installation method, then? Chocolatey?

**Comment by Redsandro** [comment]
@mrled it is explained in the [blog item](http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher) mentioned earlier.

**Comment by gep13** [comment]
This should now be taken care of.  Let me know if there are any questions.
