### ISSUE TITLE
Website side menu does not work on mobile devices

### ISSUE THREAD

**Issue by nvtkaszpir** [chocolatey/boxstarter#120]
http://boxstarter.org/WhyBoxstarter

Choosing menu options on the left does nothing.
Tried builtin browser on HTC, Firefox and Chrome. Also requesting desktop version does not fix the issue.

Sometimes Firefox manages to trigger some browser action when pressing one of the top two menu options, but it still does not trigger content change.

**Comment by dsbert** [comment]
This is also a problem on the desktop when the browser width is too small.

**Comment by dragon788** [comment]
@nvtkaszpir You can try holding your device in landscape mode, but it appears from what I'm seeing in #183 that it is definitely an issue on anything < 992px wide.

**Comment by pauby** [comment]
Tested and this is still an issue - menu buttons on the left are not clickable.

**Comment by pauby** [comment]
If @designxsteph has time then absolutely.

**Comment by designxsteph** [comment]
Yeah I see the problem is with the Bootstrap columns not being correct, which is causing content to basically overlap and break the links as well as other issues like in #183 . An easy fix would be to correct the columns, but I'd suggest also implementing a collapsable nav on mobile devices. It appears this may have been the plan as this left nav element has a class of "sidebar-offcanvas", but yet there is no css/js to support it. I'd be happy to take a look!

**Comment by pauby** [comment]
@designxsteph You are a star. Thank you!

**Comment by pauby** [comment]
PR #391 resolved.
