### ISSUE TITLE
choco install --version does not work inside BoxStarter

### ISSUE THREAD

**Issue by rgl** [chocolatey/boxstarter#164]
`choco install --version` ([like described on the choco docs](https://github.com/chocolatey/choco/wiki/CommandsInstall)) does not work inside BoxStarter. BUT using `-version` (just a single dash) it works fine. So I think BoxStarter should support `--version` too.

I'm using BoxStarter 2.7.0 and Chocolatey 0.9.9.12.

Is BoxStarter "overwritting" the choco command with its own implementation? Can you point me at the source?

**Comment by mwrock** [comment]
More info poster here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chocolatey/Y9-ood-eM3M/YLkfFCsKBgAJ

**Comment by mwrock** [comment]
Boxstarter does intercept the `choco` command inorder to handle reboot scenarios. Boxstarter expects the first two parameters of choco to be the command (`install`, `update`, etc) followed by the package(s) to install and in this order. Boxstarter then forwards on all additional arguments.

This is in line with the chocolatey command line help:
```
Usage

    choco install <pkg|packages.config> [<pkg2> <pkgN>] [<options/switches>]
    cinst <pkg|packages.config> [<pkg2> <pkgN>] [<options/switches>]
```
Its likely that chocolatey may be a bit more forgiving. Also, boxstarter choco calls do not need a `-y` to be added and boxstarter will add them for you because the whole idea of boxstarter is 100% unattended installs.

**Comment by mwrock** [comment]
So you would want to change:
```
choco install -y notepad2 --version 4.2.25.3
```
to
```
choco install notepad2 --version 4.2.25.3
```

**Comment by andydix** [comment]
I'm also having a similar issue but with the --allowemptychecksum option.

I'm trying to install the dotnet4.5.1 package from a provision script run by boxstarter...

`cinst dotnet4.5.1 --allowemptychecksum`

or

`choco install dotnet4.5.1 --allowemptychecksum`

It just spits out the chocolatey help comments and fails. Using Chocolatey v0.10.0 and Boxstarter v2.8.29. Running the same command directly in PowreShell works.

Any help would be appreciated.

**Comment by andydix** [comment]
Having now looked through some other open issues, for those that have found this thread and need more info, see [this thread](https://github.com/mwrock/boxstarter/issues/198)

My particular issue of --allowemptychecksum not working has been temporarily solved by using --ignore-checksums.

Thanks.

**Comment by pauby** [comment]
As this has been resolved, alebeit with a workaround, I'm going to go ahead and close it. We can reopen this again in future if needed.
