### ISSUE TITLE
Set-BoxstarterTaskbarOptions command is missing from Boxstarter

### ISSUE THREAD

**Issue by gunther3613** [chocolatey/boxstarter#432]
### What You Are Seeing?

When using the Set-BoxstarterTaskbarOptions command Boxstarter shell through Cmdlet not found error.

"Set-BoxstarterTaskbarOptions : The term 'Set-BoxstarterTaskbarOptions' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again. ..."

I expected the Set-BoxstarterTaskbarOptions command to be found and able to be used.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Open "Boxstarter Shell"
2. Run the "Set-BoxstarterTaskbarOptions" command

### Output Log

<!--
When including the log information, please ensure you have run the command with --debug --verbose. It provides important information for determining an issue.

- Make sure there is no sensitive data shared.
- We need ALL output, not just what you may believe is relevant.
- We need ALL OUTPUT (including the configuration information)

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Set-BoxstarterTaskbarOptions : The term 'Set-BoxstarterTaskbarOptions' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ Set-BoxstarterTaskbarOptions
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-BoxstarterTaskbarOptions:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
~~~

</p>

</details>

**Comment by pauby** [comment]
In this particular version of Boxstarter the cmdlet is `Set-TaskbarOptions`. There  was a PR to change that but the version with it has not as yet been released.

**Comment by pauby** [comment]
I'm going to go ahead and close this now.

**Comment by me-kell** [comment]
The current documentation of [WinConfig](https://boxstarter.org/WinConfig) describes the command `Set-BoxstarterTaskbarOptions` even if it has not yet been released. Please do remove this from the documentation or explain that this is only in the master (as of 5. Oct 2020).
The documentation suggests downloading the version 2.12.0 which doesn't has this command

**Comment by pauby** [comment]
A new versin will be released shortly that will have that cmdlet.

**Comment by yannduran** [comment]
It's now December 28 2020, and I've just run into this problem as well. It's **very confusing and frustrating** for a new BoxStarter user!

This issue should not be closed until it is available. By closing this issue we have no way of knowing when this has been fixed. And just how long is **_shortly_** supposed to be?

**Comment by pauby** [comment]
@yannduran Before I answer that, remember you are dealing with real people here who have real lives. This is an open source project so we do what we can when we can.

* v2.13 was [released on 15 October that contains this cmdlet](https://github.com/chocolatey/boxstarter/releases/tag/v2.13.0). You can find it on the website:

![image](https://user-images.githubusercontent.com/12760779/104321403-799f8300-54db-11eb-93f6-441f8efbf058.png)

* The `Set-BoxstarterTaskbarOptions` has been updated on the [website](https://boxstarter.org/WinConfig) (second from the bottom):

![image](https://user-images.githubusercontent.com/12760779/104321565-b4a1b680-54db-11eb-8206-813d6de21ffe.png)

* The cmdlet works if you import the module or start the Boxstarter shell.
    
![image](https://user-images.githubusercontent.com/12760779/104321482-920f9d80-54db-11eb-8409-90fa02a52340.png)

Because of the above I'm not clear of the issue you are having. I've either missed something here or we've missed something with the updates. If this is still an issue, can I ask you to raise another issue as this one is closed.

**Comment by pauby** [comment]
@yannduran Could [this issue](https://github.com/chocolatey/boxstarter/issues/459) be causing what you were seeing?
