### ISSUE TITLE
remote installs do not use original nuget sources

### ISSUE THREAD

**Issue by mwrock** [chocolatey/boxstarter#6]
see https://boxstarter.codeplex.com/discussions/547713

UPDATE: Original link gone but available [here](https://web.archive.org/web/20171227030656/boxstarter.codeplex.com/discussions/547713)

**Comment by mwallner** [comment]
That discussion is gone, however the issue seems to still exist.

I've just ran into the problem that `Install-BoxstarterPackage` does not use `NugetSources` from Boxstarter Config. (also checked that `AppData\Roambing\Boxstarter` - the version of Boxstarter that is being pushed to the remote host actually contains the correct `boxstarter.config`)

as far as I've seen there is no mechanism for handling this inside https://github.com/chocolatey/boxstarter/blob/master/Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1 - maybe another/default config file is being used?
(will continue investigation...)

**Comment by mwallner** [comment]
actually, Install-BoxstarterPackage.ps1 states the observed behavior..
```
 The .nupkg file for the provided package name is searched in the following locations and order:
 - .\BuildPackages relative to the parent directory of the module file
 - The Chocolatey community feed
 This can be configured by editing $($Boxstarter.BaseDir)\Boxstarter.Config
```

**Comment by mwallner** [comment]
The "problem" seems to be the fact that the original `Boxstarter.Chocolatey\Boxstarter.zip` is being sent to the remote host - with the default boxstarter.config .. 
I take this is probably intentional?=

**Comment by mwallner** [comment]
alright - there seems to be a reason for this: when using Boxstarter to install on remote hosts (i.e. azure) - you probably won't be able to access an organization internal server .. so it makes sense to fallback to community repository + some packages on a "local feed" .. 

@mwrock @ferventcoder @gep13 @pauby 
If that's ok with you I'll put in a PR that adds another parameter `-DelegateChocolatySources` (we can talk about the name of that switch) in order to be able to pass the sources.

**Comment by pauby** [comment]
This has been merged. Closing.
