### ISSUE TITLE
new Windows Explorer settings in Windows 10

### ISSUE THREAD

**Issue by philoushka** [chocolatey/boxstarter#99]
Requesting options to set these items in Windows Explorer for Windows 10 as we get closer to Win 10 release:
- Open File Explorer to This PC
- Show recently used file in Quick access
- Show frequently used folders in Quick access

![image](https://cloud.githubusercontent.com/assets/930731/8630305/c97147b6-2718-11e5-8c6f-0c6b8bcd67a1.png)

**Comment by gep13** [comment]
@philoushka do you happen to know if there are registry keys, and values, that control these settings?  I don't have a Windows 10 VM to hand to test it out.  But finding these values would be key to getting this added into BoxStarter.

**Comment by philoushka** [comment]
Thanks Gary, I've done the research now and here are the registry details.

- **Open File Explorer to This PC**

   `[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
   "LaunchTo"=dword:0000000`

   1 for This PC,  2 for Quick Access

- **Show recent used in Quick access**
   
   `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
"ShowRecent"=dword:00000000`
   
     0 for off, 1 for on.
 
    
- **Show recent used in Quick access**
   
   `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
"ShowFrequent"=dword:00000000`
   
     0 for off, 1 for on.

**Comment by mwrock** [comment]
I approve of this feature :+1:

**Comment by gep13** [comment]
@philoushka noice! Should be very simple to bring these features into BoxStarter, given all the hard work has been done by you already!

@mwrock I think we spoke about this before, but given that BoxStarter now has functions specifically for Windows 7, 8, 8.1, and now potentially 10, should BoxStarter do some form of validation of what OS it is being run on, before applying these registry changes?

**Comment by philoushka** [comment]
I don't mind coding the change and submitting a PR if y'all have some guidance or suggestion on a similar piece of code to copy implementation from.

**Comment by gep13** [comment]
@philoushka a good place to start would be the Enable/Disable UAC scripts:

https://github.com/mwrock/boxstarter/blob/master/Boxstarter.WinConfig/Disable-UAC.ps1
https://github.com/mwrock/boxstarter/blob/master/Boxstarter.WinConfig/Enable-UAC.ps1

If you wanted to create individual enable/disable functions for each of items you have selected.

Or, you might want to think about extending the existing Set-WindowsExplorerOptions script here:

https://github.com/mwrock/boxstarter/blob/master/Boxstarter.WinConfig/Set-WindowsExplorerOptions.ps1

to include additional parameters passed in to control what gets turned on and off.

Personally, I think the latter would make most sense.

**Comment by mwrock** [comment]
I do think its getting to the point where we want to abstract these registry settings so that it is easier to add them in the future.

Regarding validation, my understanding (which could be wrong) is that if any setting is not applicable to a version of windows, adding it will not break things. So I'm not too concerned with validating, however it could provide an improved experience.

So here is a proposal for simplifying all of these windows ui settings:

We create a nested hash table that can store all the registry keys for these settings. The hash table is keyed on a "friendly" setting name and the value is another hashtable that contains the registry metadata and possible values.

Here is an example of how this might look:
```
$settings  = @{
  TaskBarDocking = @{
    key="HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects2"
    property="settings"
    values=@{
      Top="the value the will dock the task bar on the top"
      Bottom="the value the will dock the task bar on the top"
    }
  ShowHiddenFilesFoldersDrives=@{
    key="HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\advanced"
    property="Hidden"
    values=@{
      Enabled="1"
      Disabled="0"
    }
  }
}
```

Now we have just one cmdlet for tweaking all of these options called `Set-WindowsOption`. It takes an `-Option` and `-OptionValue` parameters. The `Option` param has a `ValidateSet` built from the `$settings` top level keys. `OptionValue` becomes a dynamic param based on the value names.

This would make adding registry tweaks a simple matter of adding to the `settings` hashtable.

Then we depricate the current cmdlets, which kind of sucks since this is the second time we have depricated these commands  but I think is worth it.

Thoughts?

**Comment by gep13** [comment]
Looks good to me! As you say, not ideal that it would be another overhaul of that part of the system, but I think it is justified.

**Comment by philoushka** [comment]
I'm prepping a PR for this Explorer change. I didn't find detailed tests existing for the other features. Perhaps I've missed them. 
What would you like to see in terms of tests/validation?

**Comment by mwrock** [comment]
Yeah the `WinConfig` module has no test coverage. This is another benefit of standardizing the reg entries with the above approach is that it provides an approach that is easier to test. As things stand now, we'd have to create tests for all of the options ensuring that the correct reg settings are read/set.

I'd forego tests for now. When I get around to the refactoring above, there will be tests added for that and then any new option settings can ride on top of these tests and wont need their own set unless they need to do special logic for some reason.

**Comment by pauby** [comment]
PR #100 merged.
